// Generated by CoffeeScript 1.3.3

Ext.define("MsAdmin.components.basic.Utils", {
  singleton: true,
  alternateClassName: "MsAdmin.Utils",
  translations: {
    Origin: "Translated"
  },
  translate: function(message) {
    return this.translations[message] || message;
  }
});

(function() {
  return MsAdmin.t = function(message) {
    return MsAdmin.Utils.translate(message);
  };
})();
