// Generated by CoffeeScript 1.3.3

Ext.define("app.components.actionList.view.List", {
  extend: "Ext.grid.Panel",
  constructor: function() {
    return this.addEvents({
      editiconclick: true
    });
  },
  getEditActionColumn: function() {
    return {
      xtype: "actioncolumn",
      tdCls: "list-td edit-link",
      align: "center",
      flex: .3,
      items: [
        {
          icon: MsAdmin.constants.IMAGE_PATH + "edit-icon.png",
          tooltip: "Edit",
          handler: this.onEditIconClick,
          scope: this
        }
      ]
    };
  },
  onEditIconClick: function(grid, rIdx, cIdx) {
    var selModel;
    selModel = this.getSelectionModel();
    selModel.select(rIdx);
    return this.fireEvent("editiconclick", selModel.getSelection()[0], rIdx, cIdx);
  }
});
