// Generated by CoffeeScript 1.3.3

Ext.define("app.components.actionList.view.Panel", {
  extend: "Ext.panel.Panel",
  layout: "fit",
  constructor: function(config) {
    return this.callParent([
      Ext.applyIf(config || {}, {
        items: this.getCmpItems(),
        dockedItems: this.getCmpDockedItems()
      })
    ]);
  },
  getCmpDockedItems: function() {
    return [
      {
        xtype: "toolbar",
        dock: "bottom",
        items: [
          {
            ref: "addBtn",
            text: "Add"
          }, {
            ref: "delBtn",
            text: "Delete"
          }
        ]
      }
    ];
  },
  getCmpItems: function() {}
});
