// Generated by CoffeeScript 1.3.3

Ext.define("MsAdmin.view.sensor.Sensor", {
  extend: "Ext.container.Container",
  width: 40,
  height: 40,
  cls: "sensor",
  alias: "widget.Sensor",
  constructor: function(config) {
    this.loadModel(config.model);
    this.applyStyles();
    this.addEvents({
      click: true
    });
    this.listeners = {
      render: this.initialize
    };
    return this.callParent(arguments_);
  },
  loadModel: function(record) {
    return this.record = record;
  },
  applyStyles: function(coords) {
    return this.style = {
      backgroundImage: "url('" + MsAdmin.constants.SENSOR_IMAGE_SRC + "')",
      backgroundColor: "transparent",
      backgroundRepeat: "no-repeat",
      backgroundSize: 45,
      cursor: "pointer",
      position: "absolute",
      top: this.record.get("y") + "px",
      left: this.record.get("x") + "px"
    };
  },
  initialize: function() {
    this.addDD();
    this.addCounter();
    return this.listenEvents();
  },
  addDD: function(container) {
    var me;
    me = this;
    this.dragZone = Ext.create("Ext.dd.DDProxy", this.getEl(), "sensor");
    return this.dragZone.endDrag = (function(me) {
      me;
      return function(e) {
        var del, lel;
        lel = this.getEl();
        del = this.getDragEl();
        del.style.visibility = "";
        this.beforeMove();
        lel.style.visibility = "hidden";
        Ext.dd.DDM.moveToEl(lel, del);
        del.style.visibility = "hidden";
        lel.style.visibility = "";
        this.afterDrag();
        lel = Ext.fly(lel);
        return me.getModel().set({
          x: lel.getLeft(true),
          y: lel.getTop(true)
        });
      };
    })(me);
  },
  addCounter: function() {
    var marginLeft;
    return marginLeft = this.width || this.el.getWidth();
  },
  listenEvents: function() {
    return this.el.on("click", (function() {
      return this.fireEvent("click", this);
    }), this);
  },
  getModel: function() {
    return this.model;
  }
});
