// Generated by CoffeeScript 1.3.3

Ext.define("app.mixins.FormControllerMixin", {
  markInvalid: function(form, errors) {
    var i;
    if (!(errors instanceof Ext.data.Errors)) {
      for (i in errors) {
        errors[i] = errors[i][0];
      }
    }
    return form.markInvalid(errors);
  }
});
