// Generated by CoffeeScript 1.3.3

Ext.define("MsAdmin.core.EventBus", {
  singleton: true,
  alternateClassName: "MsAdmin.Event",
  extend: "Ext.util.Observable",
  fire: function() {
    return this.fireEvent.apply(this, arguments_);
  }
});
