// Generated by CoffeeScript 1.3.3

Ext.define("MsAdmin.view.server.ServerList", {
  extend: "MsAdmin.core.widget.EditList",
  store: "Servers",
  alias: "widget.ServerList",
  constructor: function(config) {
    this.callParent([
      Ext.applyIf(config || {}, {
        columns: [
          {
            flex: .7,
            tdCls: "list-td",
            header: "Name",
            dataIndex: "name"
          }, this.getEditActionColumn()
        ]
      })
    ]);
    return this.addEvents({
      editiconclick: true
    });
  },
  getEditActionColumn: function() {
    return {
      xtype: "actioncolumn",
      tdCls: "list-td edit-link",
      align: "center",
      flex: .3,
      items: [
        {
          icon: MsAdmin.constants.IMAGE_PATH + "graphic-icon.png",
          tooltip: "Show Graphic",
          handler: this.onIconClick("graphic"),
          scope: this,
          getClass: function() {
            return "graphic-icon";
          }
        }, {
          icon: MsAdmin.constants.IMAGE_PATH + "edit-icon.png",
          tooltip: "Edit",
          handler: this.onIconClick("edit"),
          scope: this,
          getClass: function() {
            return "edit-icon";
          }
        }, {
          tooltip: "Active",
          handler: this.onIconClick("active"),
          getClass: function(htmlEl, meta, record) {
            if (record.get("active") === 0) {
              return "inactive-icon";
            } else {
              return "active-icon";
            }
          },
          scope: this
        }
      ]
    };
  }
});
