// Generated by CoffeeScript 1.3.3

Ext.define("MsAdmin.view.server.TemperatureGraphic", {
  alias: "widget.TemperatureGraphic",
  extend: "Ext.chart.Chart",
  requires: ["Ext.chart.*"],
  constructor: function(config) {
    return this.callParent([
      Ext.applyIf(config || {}, {
        animate: true,
        legend: {
          position: "bottom"
        }
      })
    ]);
  }
});
