// Generated by CoffeeScript 1.3.3

Ext.define("MsAdmin.core.widget.EditList", {
  extend: "Ext.grid.Panel",
  plugins: [
    {
      ptype: "cellediting"
    }
  ],
  constructor: function(config) {
    return this.callParent([
      Ext.applyIf(config || {}, {
        actionClicked: false,
        listeners: {
          beforeitemclick: this.onBeforeItemClick
        }
      })
    ]);
  },
  onBeforeItemClick: function() {
    if (this.actionClicked) {
      this.actionClicked = false;
      return false;
    }
  },
  getEditActionColumn: function() {
    return {
      xtype: "actioncolumn",
      tdCls: "list-td edit-link",
      align: "center",
      flex: .3,
      items: [
        {
          icon: MsAdmin.constants.IMAGE_PATH + "edit-icon.png",
          tooltip: "Edit",
          handler: this.onIconClick("edit"),
          scope: this,
          getClass: function() {
            return "edit-icon";
          }
        }, {
          tooltip: "Active",
          handler: this.onIconClick("active"),
          getClass: function(htmlEl, meta, record) {
            if (record.get("active") === 0) {
              return "inactive-icon";
            } else {
              return "active-icon";
            }
          },
          scope: this
        }
      ]
    };
  },
  onIconClick: function(actionName) {
    return function(grid, rIdx, cIdx) {
      return this.fireEvent(actionName + "iconclick", grid.getStore().getAt(rIdx), rIdx, cIdx);
    };
  },
  getActiveActionColumn: function() {
    return {
      flex: 0.1,
      header: "Active",
      align: "center",
      dataIndex: "active",
      editor: {
        inputValue: 1,
        xtype: "checkbox"
      }
    };
  }
});
